trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: PactFlowSettings

stages:

- stage: Build
  displayName: 'Build and Run Tests'
  jobs:
  - job: Build
    displayName: 'Build and Run Tests'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
      displayName: 'Setup .NET'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
      displayName: 'Restore Dependencies'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--configuration Release'
      displayName: 'Build Project'

    - task: DotNetCoreCLI@2
      env:
        PACT_BROKER_TOKEN: $(PACT_BROKER_TOKEN)
      inputs:
        command: 'test'
        projects: 'Provider.Contract.Tests/Provider.Contract.Tests.csproj'
        arguments: '--no-build --configuration Release --verbosity normal'
      displayName: 'Run Tests'

- template: can-i-deploy-template.yml
  parameters:
    pacticipant: 'StudentApi'
    environment: 'stage'

- stage: DeployAndRecordDeployment
  displayName: 'Deploy and Record Deployment'
  dependsOn: CanIDeploy
  jobs:
  - job: DeployAndRecord
    displayName: 'Deploy and Record Deployment in PactFlow'
    steps:
    - script: |
        echo "Deploying the application..."
      displayName: 'Deploy Application'

    - template: record-deployment-template.yml
      parameters:
        pacticipant: 'StudentApi'
        environment: 'stage'
