name: Contract Requiring Verification Published

trigger: none  # Disable default trigger as it’s initiated by webhook

# Define runtime parameters for PactFlow webhook data
parameters:
  - name: pact_url
    type: string
    default: ''
    displayName: 'Pact URL to verify'
  - name: sha
    type: string
    default: ''
    displayName: 'Specific commit SHA to checkout'
  - name: branch
    type: string
    default: 'refs/heads/master'
    displayName: 'Branch to Checkout'
  - name: message
    type: string
    default: ''
    displayName: 'Verification Message'

variables:
  PACT_BROKER_BASE_URL: $(PACTFLOW_BASE_URL)
  PACT_BROKER_TOKEN: $(PACTFLOW_TOKEN)
  PACT_BROKER_PUBLISH_VERIFICATIONS_RESULT: true
  BUILD_URL: "$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: ContractRequiringVerificationPublished
  displayName: "Contract Requiring Verification Published"

  steps:

  - script: echo "Verifying pact from ${{ parameters.pact_url }} - ${{ parameters.message }}"
    displayName: 'Verify Pact Message'

  - checkout: "git://BohdanTron/PactProvider@refs/heads/${{ parameters.branch }}"

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
    displayName: 'Setup .NET SDK 8.0.x'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
    displayName: 'Restore dependencies'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '--configuration Release'
    displayName: 'Build'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'Provider.Contract.Tests/Provider.Contract.Tests.csproj'
      arguments: '--no-build --configuration Release --verbosity normal'
    displayName: 'Run Provider Tests'
