name: Contract Requiring Verification Published

# Disable default trigger as it’s initiated by webhook
trigger: none
pr: none

variables:
  - group: PactFlowSettings

  - name: consumerBranch
    value: ${{ parameters.VerifyPublishedContract.client_payload.consumer_branch }}

  - name: providerBranch
    ${{ if parameters.VerifyPublishedContract.client_payload.provider_branch }}:
      value: ${{ parameters.VerifyPublishedContract.client_payload.provider_branch }}
    ${{ else }}:
      value: 'test-hook' # Should be changed to 'master'

resources:
  webhooks:
    - webhook: VerifyPublishedContract
      connection: VerifyPublishedContractConnection

  repositories:
    - repository: myrepo 
      type: github
      name: BohdanTron/PactProvider
      ref: "refs/heads/test-hook"

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: ContractRequiringVerificationPublished
    displayName: "Contract Requiring Verification Published"
    jobs:
    - job: ContractRequiringVerificationPublished
      displayName: "Contract Requiring Verification Published"
      steps:

      - checkout: myrepo
      # - script: |
      #     echo "Fetching branch: $(providerBranch)"
      #     git fetch origin $(providerBranch)
      #     git checkout $(providerBranch)
      #   displayName: "Fetch and Checkout Provider Branch"

      - script: echo "The current Build.SourceBranchName is $(Build.SourceBranchName), the provider branch is $(providerBranch)"
        displayName: "Echo Build.SourceBranchName"

      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.0.x'
        displayName: 'Setup .NET SDK 8.0.x'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
        displayName: 'Restore dependencies'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--configuration Release'
        displayName: 'Build'

      - task: DotNetCoreCLI@2
        env:
          PACT_BROKER_TOKEN: $(PACT_BROKER_TOKEN)
          PACT_BROKER_PUBLISH_VERIFICATIONS_RESULT: true
          BUILD_URL: "https://dev.azure.com/tronbodya/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
          GIT_COMMIT: $(Build.SourceVersion)
          BRANCH_NAME: $(Build.SourceBranchName)
          CONSUMER_BRANCH: ${{ parameters.VerifyPublishedContract.client_payload.consumer_branch }}
        inputs:
          command: 'test'
          projects: 'Provider.Contract.Tests/Provider.Contract.Tests.csproj'
          arguments: '--no-build --configuration Release --verbosity normal'
        displayName: 'Run Provider Tests'
