# Disable default trigger as it’s initiated by webhook
trigger: none
pr: none

resources:
  webhooks:
    - webhook: TestHook
      connection: TestHookConnection

variables:
  - group: PactFlowSettings

  - name: consumerBranch
    value: ${{ parameters.TestHook.client_payload.consumer_branch }}


pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: ContractRequiringVerificationPublished
    displayName: "Contract Requiring Verification Published"
    jobs:
    - job: ContractRequiringVerificationPublished
      displayName: "Contract Requiring Verification Published"
      steps:

      - checkout: self
        displayName: 'Checkout Repo'
        fetchDepth: 1
        path: s

      - script: |
          git fetch --no-tags --depth=1 origin +refs/heads/$(consumerBranch):refs/remotes/origin/$(consumerBranch)
          git checkout $(consumerBranch) || git checkout master
        displayName: 'Ensure branch and fallback to master'

      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.0.x'
        displayName: 'Setup .NET SDK 8.0.x'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
        displayName: 'Restore dependencies'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--configuration Release'
        displayName: 'Build'

      - task: DotNetCoreCLI@2
        env:
          PACT_BROKER_TOKEN: $(PACT_BROKER_TOKEN)
          PACT_BROKER_PUBLISH_VERIFICATIONS_RESULT: true
          BUILD_URL: "https://dev.azure.com/tronbodya/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
          GIT_COMMIT: $(Build.SourceVersion)
          BRANCH_NAME: $(Build.SourceBranchName)
          CONSUMER_BRANCH: ${{ parameters.TestHook.client_payload.consumer_branch }}
        inputs:
          command: 'test'
          projects: 'Provider.Contract.Tests/Provider.Contract.Tests.csproj'
          arguments: '--no-build --configuration Release --verbosity normal'
        displayName: 'Run Provider Tests'
